CREATE TABLE tableName (
    ID	INT,
    Nombre Común	VARCHAR(512),
    Nombre Científico	VARCHAR(512),
    Familia	VARCHAR(512),
    Rango de Temperatura (°C)	VARCHAR(512),
    Rango de Humedad (%)	VARCHAR(512),
    Rango de pH	VARCHAR(512),
    Rango de Luz Solar	VARCHAR(512),
    Tipo de Tierra	VARCHAR(512),
    Requerimiento de Agua	VARCHAR(512),
    Recomendaciones Básicas	VARCHAR(512)
);

INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('1', 'Monstera Deliciosa', 'Monstera deliciosa', 'Araceae', '18 - 27', '60 - 80', '5.5 - 7.0', 'Luz indirecta', 'Bien drenado, rico en materia orgánica', 'Moderado', 'Evitar sol directo, mantener humedad uniforme.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('2', 'Palma Areca', 'Dypsis lutescens', 'Arecaceae', '18 - 24', '40 - 60', '6.0 - 7.8', 'Luz indirecta', 'Bien drenado', 'Moderado', 'No encharcar, evitar corrientes de aire.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('3', 'Sansevieria', 'Sansevieria trifasciata', 'Asparagaceae', '15 - 30', '30 - 50', '4.5 - 8.5', 'Luz indirecta', 'Arenoso, bien drenado', 'Bajo', 'Tolera poca luz, riegos espaciados.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('4', 'Ficus Lyrata
', 'Ficus lyrata', 'Moraceae', '16 - 24', '30 - 65', '6.0 - 7.0', 'Luz indirecta', 'Rico en nutrientes', 'Moderado', 'Evitar corrientes de aire, limpiar hojas.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('5', 'Bonsái de Naranjo', 'Citrus microcarpa', 'Rutaceae', '20 - 30', '50 - 70', '5.5 - 6.5', 'Luz solar directa', 'Para cítricos, bien drenado', 'Moderado', 'Requiere poda regular, fertilización mensual.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('6', 'Orquídea Phalaenopsis', 'Phalaenopsis spp.', 'Orchidaceae', '18 - 25', '50 - 70', '5.5 - 6.5', 'Luz indirecta', 'Sustrato especial orquídeas', 'Moderado', 'No encharcar, regar en la mañana.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('7', 'Anturio', 'Anthurium andraeanum', 'Araceae', '20 - 25', '60 - 80', '5.5 - 6.5', 'Luz indirecta', 'Rico en materia orgánica', 'Moderado', 'Mantener humedad sin exceso de agua.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('8', 'Bromelia', 'Bromelia spp.', 'Bromeliaceae', '15 - 30', '50 - 70', '5.0 - 6.0', 'Luz indirecta', 'Bien drenado', 'Moderado', 'Regar en el centro de la roseta.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('9', 'Begonia', 'Begonia spp.', 'Begoniaceae', '18 - 24', '60 - 70', '5.5 - 6.5', 'Luz indirecta', 'Rico en materia orgánica', 'Moderado', 'No mojar hojas, podar regularmente.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('10', 'Lirio', 'Lilium spp.', 'Liliaceae', '15 - 23', '40 - 60', '6.0 - 6.5', 'Luz solar directa', 'Bien drenado, ácido', 'Moderado', 'Regar sin encharcar, cortar flores marchitas.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('11', 'Margarita', 'Leucanthemum vulgare', 'Leucanthemum vulgare', '15 - 24', '40 - 60', '6.0 - 8.0', 'Luz solar directa', 'Bien drenado, fértil', 'Moderado', 'Regar cuando el suelo esté seco.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('12', 'Petunia', 'Petunia spp.', 'Solanaceae', '18 - 24', '40 - 70', '6.0 - 7.5', 'Luz solar directa', 'Arenoso, bien drenado', 'Moderado', 'Regar regularmente, quitar flores marchitas.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('13', 'Lavanda', 'Lavandula spp.', 'Lamiaceae', '15 - 25', '40 - 60', '6.5 - 7.5', 'Luz solar directa', 'Rico en materia orgánica', 'Bajo', 'Evitar suelos húmedos, podar tras floración.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('14', 'Helecho', 'Nephrolepis exaltata', 'Nephrolepidaceae', '18 - 24', '60 - 80', '5.0 - 5.5', 'Luz indirecta', 'Arenoso, bien drenado', 'Alto', 'Mantener humedad sin encharcar.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('15', 'Cactus', 'Cactaceae spp.', 'Cactaceae', '15 - 35', '20 - 40', '5.0 - 7.0', 'Luz solar directa', 'Arenoso, bien drenado', 'Bajo', 'Regar esporádicamente, evitar exceso de agua.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('16', 'Suculenta', 'Crassula spp.', 'Crassulaceae', '15 - 30', '20 - 50', '5.5 - 7.5', 'Luz solar directa', 'Rico en materia orgánica', 'Bajo', 'Regar cuando el sustrato esté seco.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('17', 'Jazmín', 'Jasminum spp.', 'Oleaceae', '15 - 28', '40 - 60', '40 - 60', 'Luz solar directa', 'Rico en materia orgánica', 'Moderado', 'Podar regularmente, mantener suelo húmedo.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('18', 'Hortensia', 'Hydrangea spp.', 'Hydrangeaceae', '13 - 22', '50 - 80', '5.0 - 6.5', 'Luz indirecta', 'Rico en materia orgánica', 'Moderado', 'Sensible al pH del suelo, mantener humedad constante.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('19', 'Geranio', 'Pelargonium spp.', 'Geraniaceae', '15 - 25', '40 - 60', '5.5 - 7.0', 'Luz solar directa', 'Bien drenado', 'Moderado', 'Regar moderadamente, podar flores secas.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('20', 'Rosas', 'Rosa spp.', 'Rosaceae', '13 - 25', '40 - 70', '6.0 - 7.0', 'Luz solar directa', 'Rico en nutrientes', 'Moderado', 'Podar regularmente, fertilizar en época de crecimiento.');
INSERT INTO tableName (ID, Nombre Común, Nombre Científico, Familia, Rango de Temperatura (°C), Rango de Humedad (%), Rango de pH, Rango de Luz Solar, Tipo de Tierra, Requerimiento de Agua, Recomendaciones Básicas) VALUES ('', '', '', '', '', '', '', '', '', '', '');
